DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
SET search_path TO public;

\c bookstore;

-- USERS TABLE
DROP TABLE IF EXISTS USERS;

DROP TYPE IF EXISTS USER_ROLE;

CREATE TYPE USER_ROLE AS ENUM (
  'ADMIN',
  'USER'
);

CREATE TABLE USERS (
  ID UUID PRIMARY KEY DEFAULT uuidv7(),
  USERNAME VARCHAR(20) UNIQUE NOT NULL,
  PASSWORD VARCHAR(20) NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  ROLE USER_ROLE DEFAULT 'USER' NOT NULL,
  CREATE_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
  UPDATE_DATE TIMESTAMP DEFAULT NOW() NOT NULL
);

INSERT INTO USERS (USERNAME, PASSWORD, NAME, ROLE) VALUES ('admin','admin@123', 'admin bookstore', 'ADMIN');

-- BOOKS TABLE
DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS (
    ID UUID PRIMARY KEY DEFAULT uuidv7(),
    TITLE VARCHAR(100) NOT NULL,
    AUTHOR VARCHAR(50) NOT NULL,
    PRICE DECIMAL(12,2),
    STOCK SMALLINT,
    CREATE_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATE_DATE TIMESTAMP DEFAULT NOW() NOT NULL
);

-- ORDERS TABLE
DROP TABLE IF EXISTS ORDERS;

DROP TYPE IF EXISTS ORDER_STATUS;

CREATE TYPE STATUS_TYPE AS ENUM (
  'PENDING',
  'PAID',
  'CANCELLED'
);

CREATE TABLE ORDERS (
    ID UUID PRIMARY KEY DEFAULT uuidv7(),
    USERS_ID UUID NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY (USERS_ID) REFERENCES USERS(ID),
    TOTAL_PRICE DECIMAL(12,2),
    ORDER_STATUS STATUS_TYPE DEFAULT 'PENDING' NOT NULL,
    CREATE_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATE_DATE TIMESTAMP DEFAULT NOW() NOT NULL
);

-- ORDER_ITEMS TABLE
DROP TABLE IF EXISTS ORDER_ITEMS;

CREATE TABLE ORDER_ITEMS (
    ID UUID PRIMARY KEY DEFAULT uuidv7(),
    ORDER_ID UUID NOT NULL,
    BOOK_ID UUID NOT NULL,
    CONSTRAINT fk_order FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
    CONSTRAINT fk_book FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID),
    QUANTITY SMALLINT,
    PRICE DECIMAL(12,2),
    CREATE_DATE TIMESTAMP DEFAULT NOW() NOT NULL, --JOIN TIME
    LAST_READ TIMESTAMP DEFAULT NOW() NOT NULL
);
